<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>multi-module-project</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <!-- build order will follow this list -->
    <modules>
        <module>module3-repository</module>
        <module>module2-service</module>
        <module>module1-user</module>
    </modules>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.11.0</version>
                    <configuration>
                        <release>${maven.compiler.release}</release>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>com.github.spotbugs</groupId>
                <artifactId>spotbugs-maven-plugin</artifactId>
                <version>4.7.3.0</version>
                <executions>
                    <execution>
                        <id>spotbugs-generate-reports</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>spotbugs</goal>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>

                    <failOnError>false</failOnError>
                    <effort>Default</effort>
                    <threshold>Low</threshold>
                    <includeTests>false</includeTests>
                    <xmlOutput>true</xmlOutput>
                    <spotbugsXmlOutputDirectory>${project.basedir}/spotbugs</spotbugsXmlOutputDirectory>
                    <!-- Name each file after the module's artifactId -->
                    <spotbugsXmlOutputFilename>${project.artifactId}-spotbugs.xml</spotbugsXmlOutputFilename>

                    <plugins>
                        <plugin>
                            <groupId>com.h3xstream.findsecbugs</groupId>
                            <artifactId>findsecbugs-plugin</artifactId>
                            <version>1.12.0</version>
                        </plugin>
                    </plugins>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>gather-spotbugs-reports</id>
                        <phase>verify</phase>
                        <configuration>
                            <target>
                                <mkdir dir="${basedir}/spotbugs" />
                                <copy todir="${basedir}/spotbugs" flatten="true">
                                    <fileset dir="${basedir}">
                                        <include name="**/spotbugs/*-spotbugs.xml" />
                                    </fileset>
                                </copy>
                            </target>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

        </plugins>


    </build>
</project>
